language: go

go:
- master

before_install:
  - go get github.com/mitchellh/gox
 
script:
#  - go build
  - gox -os="linux" -arch="amd64" -output="travis-test.."  -verbose ./
  - ls -l
  
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "$githubtoken"
  file:
  - travis-test
  on:
    tags: true

